# Base packages installed on all systems
# These packages are included regardless of host or modules

description: Base system packages

packages:
  # Essential base system
  - base
  - base-devel
  - git
  - stow

  # dcli dependencies
  - paru         # AUR helper (required for AUR package management)
  - fzf          # Fuzzy finder (required for dcli search/module/backup TUI)
  - timeshift    # System backup tool (required for dcli backup commands)
