#!/bin/bash

state_file="${XDG_RUNTIME_DIR:-/run/user/$UID}/hypr-osu-mode"

if [[ -f "$state_file" ]]; then
  echo '{"text": "OSU", "tooltip": "OSU Mode On", "class": "active"}'
else
  echo '{"text": ""}'
fi
