#!/bin/bash

# Exit early if we don't have the tte show
if ! command -v tte &>/dev/null; then
  exit 1
fi

# Exit early if screensave is already running
pgrep -f "ghostty.*Screensaver" && exit 0

focused=$(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name')

for m in $(hyprctl monitors -j | jq -r '.[] | .name'); do
  hyprctl dispatch focusmonitor $m

  hyprctl dispatch exec -- \
    ghostty --title Screensaver -e ~/.config/hypr/scripts/screensaver
done

hyprctl dispatch focusmonitor $focused
