#!/bin/bash

STATE_FILE="/tmp/focus-mode-state"

workspace_id=$(hyprctl activeworkspace -j | jq -r .id)
gaps=$(hyprctl workspacerules -j | jq -r ".[] | select(.workspaceString == \"$workspace_id\") | .gapsOut[0] // 0")

if [[ $gaps == "0" ]]; then
	# Switch to Vibe Mode
	hyprctl keyword "workspace $workspace_id, gapsout:10, gapsin:4, bordersize:2"
	hyprctl keyword decoration:rounding 15
	hyprctl keyword animations:enabled true

	if [[ -f "$HOME/.config/ghostty/config" ]]; then
		sed -i 's/background-opacity = 1$/background-opacity = 0.65/g' "$HOME/.config/ghostty/config"
		pkill -SIGUSR2 -x ghostty
	fi
	restart-app waybar

	rm -f "$STATE_FILE"
	notify-send "Vibe Mode"
else
	# Switch to Focus Mode
	hyprctl keyword "workspace $workspace_id, gapsout:0, gapsin:0, bordersize:1"
	hyprctl keyword decoration:rounding 0
	hyprctl keyword animations:enabled false

	if [[ -f "$HOME/.config/ghostty/config" ]]; then
		sed -i 's/background-opacity = 0\\.65$/background-opacity = 1/g' "$HOME/.config/ghostty/config"
		pkill -SIGUSR2 -x ghostty
	fi
	pkill waybar

	touch "$STATE_FILE"
	notify-send "Focus Mode"
fi
